// Generated by   : UTFTConverter v0.1
// Generated from : smiley_tongue_24.jpg
// Time generated : 2017-04-24 16:31:50.352856 UTC
// Image Size     : 24x24 pixels
// Memory usage   : 1152 bytes

#if defined(__AVR__)
    #include <avr/pgmspace.h>
#elif defined(__PIC32MX__)
    #define PROGMEM
#elif defined(__arm__)
    #define PROGMEM
#endif

const unsigned short bitmap24[576] PROGMEM={0x0000,   // 0x0230 (560) pixels
0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000,   // 0x0240 (576) pixels
};
