// Generated by   : UTFTConverter v0.1
// Generated from : google.jpg
// Time generated : 2018-02-08 06:09:41.424425 UTC
// Image Size     : 32x32 pixels
// Memory usage   : 2048 bytes

#if defined(__AVR__)
    #include <avr/pgmspace.h>
#elif defined(__PIC32MX__)
    #define PROGMEM
#elif defined(__arm__)
    #define PROGMEM
#endif

const unsigned short bitmap32[1024] PROGMEM={ 0xFFFF, 0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFFFF,0xFF00  // 0x0400 (1024) pixels
};
